# Generated by Django 3.2 on 2022-02-04 11:22

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_manager', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_parent', models.BooleanField(default=False, verbose_name='والدین')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='دبیر')),
                ('is_student', models.BooleanField(default=False, verbose_name='دانش آموز')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[main.validators.is_valid_national_code], verbose_name='کد ملی')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='account/', verbose_name='تصویر پروفایل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('father_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام پدر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('date_of_birth', models.CharField(max_length=200, verbose_name='تاریخ تولد')),
                ('home_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن منزل')),
                ('job', models.CharField(blank=True, max_length=120, null=True, verbose_name='شغل')),
                ('education', models.CharField(blank=True, max_length=120, null=True, verbose_name='تحصیلات')),
                ('work_address', models.TextField(blank=True, null=True, verbose_name='آدرس محل کار')),
                ('work_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن محل کار')),
                ('certificate_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد شناسنامه')),
                ('university', models.CharField(blank=True, max_length=120, null=True, verbose_name='دانشگاه محل تحصیل')),
                ('working_hours', models.FloatField(blank=True, null=True, verbose_name='تعداد ساعت های کار')),
                ('basic_salary', models.FloatField(blank=True, null=True, verbose_name='حقوق پایه')),
                ('single_or_married', models.CharField(blank=True, choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=120, null=True, verbose_name='مجرد یا متاهل')),
                ('child_num', models.IntegerField(blank=True, null=True, verbose_name='تعداد فرزند')),
                ('spouse_fullname', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی همسر')),
                ('spouse_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همسر')),
                ('status', models.CharField(blank=True, choices=[('نیرو آزاد', 'نیرو آزاد'), ('شاغل آموزش و پرورش', 'شاغل آموزش و پرورش'), ('مامور آموزش و پرورش', 'مامور آموزش و پرورش'), ('حق التدریس', 'حق التدریس'), ('بازنشسته', 'بازنشسته')], max_length=120, null=True, verbose_name='وضعیت')),
            ],
            options={
                'ordering': ('last_name',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
