# Generated by Django 3.2 on 2022-02-19 05:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('ساده', 'ساده'), ('متوسط', 'متوسط'), ('سخت', 'سخت')], max_length=5, verbose_name='سختی آزمون'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام آزمون'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='موضوع آزمون'),
        ),
        migrations.AlterField(
            model_name='quizmultipleanswers',
            name='text',
            field=models.CharField(max_length=30, verbose_name='عنوان پاسخ'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('چهار گزینه ای', 'چهار گزینه ای'), ('تشریحی', 'تشریحی')], default='چهار گزینه ای', max_length=15, verbose_name='نوع سوال'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=50, verbose_name='عنوان سوال'),
        ),
    ]
