# Generated by Django 3.2 on 2022-02-04 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='teacher',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='teacher_book', to=settings.AUTH_USER_MODEL, verbose_name='دبیر کتاب'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='books',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='books_class', to='manager.Books', verbose_name='کتاب های کلاس'),
        ),
    ]
