# Generated by Django 3.2 on 2022-02-04 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_auto_20220204_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books_class', to='manager.Books', verbose_name='کتاب های کلاس'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': True}, related_name='teacher_class', to=settings.AUTH_USER_MODEL, verbose_name='معلم کلاس'),
        ),
    ]
