# Generated by Django 3.2 on 2022-02-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20220205_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': 'رشته', 'verbose_name_plural': '04. رشته های تحصیلی'},
        ),
        migrations.AlterField(
            model_name='assign',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('حاضر', 'حاضر'), ('حاضر (با تاخیر)', 'حاضر (با تاخیر)'), ('غایب', 'غایب')], max_length=15, null=True, verbose_name='وضعیت حضور و غیاب'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='1400-11-30', max_length=50, verbose_name='تاریخ کلاس'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام کتاب درسی'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=15, verbose_name='نام کلاس'),
        ),
        migrations.AlterField(
            model_name='employmentform',
            name='organ',
            field=models.CharField(max_length=25, verbose_name='ارگان مورد نظر'),
        ),
        migrations.AlterField(
            model_name='employmentform',
            name='status',
            field=models.CharField(choices=[('بررسی شده', 'بررسی شده'), ('در انتظار بررسی', 'در انتظار بررسی'), ('رد شده', 'رد شده')], default='در انتظار بررسی', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='backgroundColor',
            field=models.CharField(max_length=15, verbose_name='رنگ زمینه رویداد'),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='borderColor',
            field=models.CharField(max_length=15, verbose_name='رنگ خط رویداد'),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='توضیحات رویداد'),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='آیدی رویدار'),
        ),
        migrations.AlterField(
            model_name='eventcalendar',
            name='title',
            field=models.CharField(max_length=10, verbose_name='عنوان رویداد'),
        ),
        migrations.AlterField(
            model_name='externaleventcalendar',
            name='backgroundColor',
            field=models.CharField(max_length=15, verbose_name='رنگ زمینه رویداد'),
        ),
        migrations.AlterField(
            model_name='externaleventcalendar',
            name='borderColor',
            field=models.CharField(max_length=15, verbose_name='رنگ خط رویداد'),
        ),
        migrations.AlterField(
            model_name='externaleventcalendar',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='آیدی رویدار'),
        ),
        migrations.AlterField(
            model_name='externaleventcalendar',
            name='title',
            field=models.CharField(max_length=10, verbose_name='عنوان رویداد'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=10, verbose_name='نام مقطع'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, max_length=120, verbose_name='شرح تکلیف'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=10, verbose_name='نام رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='noticebox',
            name='description',
            field=models.TextField(max_length=300, verbose_name='متن اعلان'),
        ),
        migrations.AlterField(
            model_name='noticebox',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان اعلان'),
        ),
    ]
