# Generated by Django 3.2 on 2022-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220219_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='1401-03-24', max_length=50, verbose_name='تاریخ کلاس'),
        ),
    ]
